# Generated by Django 4.2.5 on 2023-09-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoBombero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vehiculo', models.CharField(max_length=100)),
                ('estado_actual', models.CharField(max_length=50)),
                ('responsable_asignado', models.CharField(blank=True, max_length=100)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('mantenimiento_programado', models.BooleanField(default=False)),
                ('fecha_mantenimiento_programado', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('imagen', models.ImageField(null=True, upload_to='imgprod')),
            ],
        ),
    ]
