# Generated by Django 4.2.5 on 2023-09-30 00:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoBombero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(default='Desconocido', max_length=20)),
                ('patente', models.CharField(default='Desconocido', max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('compañia', models.CharField(max_length=100)),
                ('imagen', models.ImageField(null=True, upload_to='imgprod')),
            ],
        ),
        migrations.CreateModel(
            name='MantencionVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometraje', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nro_motor', models.CharField(max_length=50)),
                ('nro_chasis', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('numero_orden_compra', models.CharField(max_length=50)),
                ('nombre_mandante', models.CharField(max_length=100)),
                ('nombre_mecanico', models.CharField(max_length=100)),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('costo_total_mantencion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion_carro', models.TextField()),
                ('estado_carro', models.CharField(choices=[('Disponible', 'Disponible'), ('No Disponible', 'No Disponible'), ('En Mantencion', 'En Mantencion')], default='Disponible', max_length=20)),
                ('tipo_motor', models.CharField(choices=[('Diesel', 'Diesel'), ('Gasolina', 'Gasolina')], max_length=10)),
                ('estado_motor', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo')], max_length=10)),
                ('estado_bateria', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo')], max_length=10)),
                ('estado_transmision', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo')], max_length=10)),
                ('estado_caja_direccion', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo')], max_length=10)),
                ('estado_diferencial', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo')], max_length=10)),
                ('id_autobombero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_bomberos.autobombero')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('capitan', 'Capitán'), ('mecanico', 'Mecánico'), ('comandante', 'Comandante')], default='mecanico', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
