# Generated by Django 4.2.5 on 2023-09-26 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bomberos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autobombero',
            old_name='estado_actual',
            new_name='tipo_de_vehiculo',
        ),
        migrations.RemoveField(
            model_name='autobombero',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='autobombero',
            name='fecha_mantenimiento_programado',
        ),
        migrations.RemoveField(
            model_name='autobombero',
            name='fecha_ultima_actualizacion',
        ),
        migrations.RemoveField(
            model_name='autobombero',
            name='mantenimiento_programado',
        ),
        migrations.RemoveField(
            model_name='autobombero',
            name='nombre_vehiculo',
        ),
        migrations.RemoveField(
            model_name='autobombero',
            name='responsable_asignado',
        ),
        migrations.AddField(
            model_name='autobombero',
            name='patente',
            field=models.CharField(default='Desconocido', max_length=20),
        ),
    ]
