# Generated by Django 4.2.5 on 2023-09-26 00:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_bomberos', '0002_rename_estado_actual_autobombero_tipo_de_vehiculo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MantencionVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometraje', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nro_motor', models.CharField(max_length=50)),
                ('nro_chasis', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('numero_orden_compra', models.CharField(max_length=50)),
                ('nombre_mandante', models.CharField(max_length=100)),
                ('nombre_mecanico', models.CharField(max_length=100)),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('costo_total_mantencion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion_carro', models.TextField()),
                ('estado_carro', models.CharField(choices=[('Disponible', 'Disponible'), ('No Disponible', 'No Disponible'), ('En Mantencion', 'En Mantencion')], default='Disponible', max_length=20)),
                ('tipo_motor', models.CharField(choices=[('Diesel', 'Diesel'), ('Gasolina', 'Gasolina')], max_length=10)),
                ('estado_motor', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo')], max_length=10)),
                ('estado_bateria', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo')], max_length=10)),
                ('estado_transmision', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo')], max_length=10)),
                ('estado_caja_direccion', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo')], max_length=10)),
                ('estado_diferencial', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo')], max_length=10)),
                ('id_autobombero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_bomberos.autobombero')),
            ],
        ),
    ]
