# Generated by Django 4.2.5 on 2023-09-30 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_bomberos', '0003_compañia_delete_compañía_alter_autobombero_compañia'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='compañia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_bomberos.compañia'),
        ),
    ]
