# Generated by Django 4.2.5 on 2023-10-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bomberos', '0004_customuser_compañia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantencionvehiculo',
            name='costo_total_mantencion',
        ),
        migrations.RemoveField(
            model_name='mantencionvehiculo',
            name='descripcion_carro',
        ),
        migrations.RemoveField(
            model_name='mantencionvehiculo',
            name='estado_bateria',
        ),
        migrations.RemoveField(
            model_name='mantencionvehiculo',
            name='estado_caja_direccion',
        ),
        migrations.RemoveField(
            model_name='mantencionvehiculo',
            name='estado_carro',
        ),
        migrations.RemoveField(
            model_name='mantencionvehiculo',
            name='estado_diferencial',
        ),
        migrations.RemoveField(
            model_name='mantencionvehiculo',
            name='estado_motor',
        ),
        migrations.RemoveField(
            model_name='mantencionvehiculo',
            name='estado_transmision',
        ),
        migrations.RemoveField(
            model_name='mantencionvehiculo',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='mantencionvehiculo',
            name='kilometraje',
        ),
        migrations.RemoveField(
            model_name='mantencionvehiculo',
            name='nombre_mandante',
        ),
        migrations.RemoveField(
            model_name='mantencionvehiculo',
            name='nombre_mecanico',
        ),
        migrations.RemoveField(
            model_name='mantencionvehiculo',
            name='nombre_proveedor',
        ),
        migrations.RemoveField(
            model_name='mantencionvehiculo',
            name='nro_chasis',
        ),
        migrations.RemoveField(
            model_name='mantencionvehiculo',
            name='nro_motor',
        ),
        migrations.RemoveField(
            model_name='mantencionvehiculo',
            name='numero_orden_compra',
        ),
        migrations.RemoveField(
            model_name='mantencionvehiculo',
            name='tipo_motor',
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='estado_bornes_terminales_bateria',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Malo', 'Malo'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='estado_carroceria',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Malo', 'Malo'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='estado_combustible',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Malo', 'Malo'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='estado_filtro_aire',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Malo', 'Malo'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='estado_frenos_estacionamiento',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Malo', 'Malo'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='estado_frenos_servicio_funcionamiento',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Malo', 'Malo'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='estado_fugas_aceite_aire',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Malo', 'Malo'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='estado_fugas_aire',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Malo', 'Malo'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='estado_fugas_general_funcionamiento_bomba',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Malo', 'Malo'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='estado_lecturas_manometros_manovacuometros',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Malo', 'Malo'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='estado_liquido_fugas',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Malo', 'Malo'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='estado_liquido_juego_direccion',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Malo', 'Malo'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='estado_llantas',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Malo', 'Malo'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='estado_luces_altas_bajas',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Malo', 'Malo'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='estado_luces_emergencia',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Malo', 'Malo'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='estado_luces_estacionamiento_viraje',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Malo', 'Malo'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='estado_luces_reserva_alarma_retroceso',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Malo', 'Malo'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='estado_luces_tablero_bomba',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Malo', 'Malo'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='estado_luces_traseras_frenos',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Malo', 'Malo'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='estado_motor_funcionamiento',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Malo', 'Malo'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='estado_nivel_aceite_motor',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Malo', 'Malo'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='estado_nivel_aceite_transmision',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Malo', 'Malo'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='estado_nivel_liquido_hidraulico',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Malo', 'Malo'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='estado_nivel_refrigerante',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Malo', 'Malo'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='estado_parabrisas_ventanas',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Malo', 'Malo'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='estado_presion_desgaste_neumaticos',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Malo', 'Malo'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='estado_pto_enganche_bomba',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Malo', 'Malo'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='estado_sistemas_sonoros_emergencia',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Malo', 'Malo'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='estado_tablero_instrumentos',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Malo', 'Malo'), ('N/A', 'N/A')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='hora_entrada',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='hora_salida',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='observaciones',
            field=models.TextField(default='Sin observaciones'),
        ),
    ]
