# Generated by Django 4.2.5 on 2023-10-04 23:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_bomberos', '0005_remove_mantencionvehiculo_costo_total_mantencion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
