# Generated by Django 4.2.5 on 2023-10-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bomberos', '0006_mantencionvehiculo_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='tipo_interno_mantencion',
            field=models.CharField(choices=[('preventiva', 'Preventiva'), ('correctiva', 'Correctiva')], default='preventiva', max_length=10),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='tipo_mantencion',
            field=models.CharField(choices=[('interna', 'Interna'), ('externa', 'Externa')], default='interna', max_length=10),
        ),
    ]
