# Generated by Django 4.2.5 on 2023-10-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bomberos', '0009_alter_mantencionvehiculo_tipo_interno_mantencion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantencionvehiculo',
            name='tipo_interno_mantencion',
            field=models.CharField(choices=[('Preventiva', 'Preventiva'), ('Correctiva', 'Correctiva'), ('Sin especificar', 'Sin especificar')], default='Sin especificar', max_length=20),
        ),
        migrations.AlterField(
            model_name='mantencionvehiculo',
            name='tipo_mantencion',
            field=models.CharField(choices=[('Interna', 'Interna'), ('Externa', 'Externa'), ('Sin especificar', 'Sin especificar')], default='Sin especificar', max_length=20),
        ),
    ]
