# Generated by Django 4.2.5 on 2023-10-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bomberos', '0010_alter_mantencionvehiculo_tipo_interno_mantencion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantencionvehiculo',
            name='tipo_interno_mantencion',
        ),
        migrations.AlterField(
            model_name='mantencionvehiculo',
            name='tipo_mantencion',
            field=models.CharField(choices=[('Preventiva', 'Preventiva'), ('Correctiva', 'Correctiva'), ('Externa', 'Externa')], default='Correctiva', max_length=20),
        ),
    ]
