# Generated by Django 4.2.5 on 2023-10-06 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_bomberos', '0011_remove_mantencionvehiculo_tipo_interno_mantencion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mantencionvehiculo',
            old_name='fecha',
            new_name='fecha_correctiva',
        ),
        migrations.RenameField(
            model_name='mantencionvehiculo',
            old_name='hora_entrada',
            new_name='hora_entrada_correctiva',
        ),
        migrations.RenameField(
            model_name='mantencionvehiculo',
            old_name='hora_salida',
            new_name='hora_entrada_externa',
        ),
        migrations.RenameField(
            model_name='mantencionvehiculo',
            old_name='observaciones',
            new_name='observaciones_correctiva',
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='fecha_externa',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='fecha_preventiva',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='hora_entrada_preventiva',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='hora_salida_correctiva',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='hora_salida_externa',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='hora_salida_preventiva',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='observaciones_externa',
            field=models.TextField(default='Sin observaciones'),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='observaciones_preventiva',
            field=models.TextField(default='Sin observaciones'),
        ),
    ]
