# Generated by Django 4.2.5 on 2023-10-06 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bomberos', '0012_rename_fecha_mantencionvehiculo_fecha_correctiva_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantencionvehiculo',
            name='hora_entrada_externa',
        ),
        migrations.RemoveField(
            model_name='mantencionvehiculo',
            name='hora_salida_externa',
        ),
    ]
