# Generated by Django 4.2.5 on 2023-10-07 22:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bomberos', '0013_remove_mantencionvehiculo_hora_entrada_externa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autobombero',
            name='año',
            field=models.IntegerField(default=1900, validators=[django.core.validators.MinValueValidator(1900)]),
        ),
        migrations.AddField(
            model_name='autobombero',
            name='marca',
            field=models.CharField(default='Desconocido', max_length=50),
        ),
        migrations.AddField(
            model_name='autobombero',
            name='nro_chasis',
            field=models.CharField(default='Sin especificar', max_length=150),
        ),
        migrations.AddField(
            model_name='autobombero',
            name='nro_motor',
            field=models.CharField(default='Sin especificar', max_length=100),
        ),
        migrations.AddField(
            model_name='autobombero',
            name='tipo_vehiculo',
            field=models.CharField(default='Desconocido', max_length=50),
        ),
    ]
