# Generated by Django 4.2.5 on 2023-10-08 06:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_bomberos', '0014_autobombero_año_autobombero_marca_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mantencionvehiculo',
            old_name='fecha_preventiva',
            new_name='fecha_preventiva_entrega',
        ),
        migrations.RenameField(
            model_name='mantencionvehiculo',
            old_name='hora_entrada_correctiva',
            new_name='hora_bomba_correctiva',
        ),
        migrations.RenameField(
            model_name='mantencionvehiculo',
            old_name='hora_entrada_preventiva',
            new_name='hora_bomba_preventiva',
        ),
        migrations.RenameField(
            model_name='mantencionvehiculo',
            old_name='hora_salida_correctiva',
            new_name='hora_motor_correctiva',
        ),
        migrations.RenameField(
            model_name='mantencionvehiculo',
            old_name='hora_salida_preventiva',
            new_name='hora_motor_preventiva',
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='fecha_preventiva_ingreso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mantencionvehiculo',
            name='kilometraje',
            field=models.IntegerField(default=0),
        ),
    ]
